Repository brendt/rfc-vote, pull requests merged in 2023-10, with the labels that each got.

#323 Removed blade files in auth dir
  app/Http/Controllers/LoginController.php
  app/Http/Controllers/LogoutController.php
  app/Http/Controllers/RegisterController.php
  resources/markdown/policy.md
  resources/markdown/terms.md
  resources/views/auth/login.blade.php
  resources/views/auth/logout.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/two-factor-challenge.blade.php
  resources/views/components/welcome.blade.php
  resources/views/dashboard.blade.php
  resources/views/login.blade.php
  resources/views/policy.blade.php
  resources/views/register-pending.blade.php
  resources/views/register.blade.php
  resources/views/terms.blade.php
  routes/web.php
Labels: dead code

#338 Renamed one-letter variable in the contributors.blade.php
  resources/views/components/about/contributors.blade.php
Labels: refactoring

#341 Fixed broken code highlight
  resources/views/layouts/base.blade.php
Labels: bug

#342 Fixed small issue with system theme
  resources/js/data/general/darkTheme.js
  resources/views/components/navbar/dark-mode-button.blade.php
Labels: bug

#344 Removed translation functions from 2 blade files
  resources/views/components/argument-card/card-footer.blade.php
  resources/views/rfc.blade.php
Labels: refactoring

#359 Moved tutorial to about page
  app/Models/User.php
  resources/views/about.blade.php
  resources/views/components/about/section.blade.php
  resources/views/components/icons/question-mark-circle.blade.php
  resources/views/components/rfc/tutorial.blade.php
  resources/views/rfc.blade.php
Labels: ux/ui

#366 Added dark theme to markdown editor
  resources/css/_fixes.css
  resources/css/_theme.scss
  resources/css/app.css
  resources/css/easymde.css
  resources/views/rfc.blade.php
  vite.config.js
Labels: ux/ui
