Repository brendt/rfc-vote, pull requests merged in 2023-09, with the labels that each got.

#281 🎨 Footer re-design
  resources/views/components/footer.blade.php
  resources/views/components/footer/footer.blade.php
  resources/views/components/footer/link.blade.php
  resources/views/components/icons/document.blade.php
  resources/views/components/icons/github.blade.php
  resources/views/components/icons/rss.blade.php
  resources/views/components/icons/youtube.blade.php
  resources/views/layouts/base.blade.php
Labels: Feedback wanted

#287 Fixed text that was black on dark background
  resources/views/livewire/message-list.blade.php
Labels: bug

#289 Renamed publicProfile.blade.php to public-profile.blade.php
  app/Http/Controllers/PublicProfileController.php
  resources/views/public-profile.blade.php
Labels: refactoring

#290 Added Tippy.js to the project
  package-lock.json
  package.json
  resources/css/app.css
  resources/js/app.js
  resources/views/components/argument-card/share-link.blade.php
  resources/views/components/argument-card/share-links.blade.php
  resources/views/components/profile/flair.blade.php
Labels: ux/ui, feature

#288 Admin navbar redesign to a sidebar
  resources/views/components/admin-sidebar/link.blade.php
  resources/views/components/admin-sidebar/sidebar.blade.php
  resources/views/components/icons/check-circle.blade.php
  resources/views/components/icons/rectangle-stack.blade.php
  resources/views/components/icons/users.blade.php
  resources/views/components/navbar/navbar.blade.php
  resources/views/layouts/admin.blade.php
Labels: ux/ui

#295 Argument card style fixes
  resources/views/components/argument-card/card.blade.php
  resources/views/components/argument-card/options.blade.php
  resources/views/components/argument-card/vote.blade.php
  resources/views/components/buttons/more-options.blade.php
  resources/views/components/message-card/options.blade.php
Labels: ux/ui

#291 Moved 'Add a new comment' title to a comment-form.blade.php component
  resources/views/argument-comments.blade.php
  resources/views/components/argument-card/comment-form.blade.php
Labels: ux/ui

#292 Changed info message when you create comment
  resources/views/layouts/base.blade.php
Labels: ux/ui

#297 Refactored profile-form into 4 blade components
  resources/views/components/profile/settings/email.blade.php
  resources/views/components/profile/settings/password.blade.php
  resources/views/components/profile/settings/profile.blade.php
  resources/views/components/profile/settings/verification.blade.php
  resources/views/profile-form.blade.php
Labels: refactoring

#298 Changed the profile settings layout into 2 columns
  resources/views/components/form/wrapper.blade.php
  resources/views/profile-form.blade.php
Labels: ux/ui

#307 New profile avatar uploader
  resources/js/app.js
  resources/js/data/profile/avatarSettings.js
  resources/views/components/icons/camera.blade.php
  resources/views/components/profile/header.blade.php
  resources/views/components/profile/settings/file-uploader.blade.php
  resources/views/components/profile/settings/profile.blade.php
Labels: ux/ui

#308 Dark theme small fixes
  resources/views/components/buttons/github.blade.php
  resources/views/components/buttons/main.blade.php
  resources/views/components/checkbox.blade.php
  resources/views/login.blade.php
  resources/views/register.blade.php
Labels: ux/ui

#286 More end to end tests
  .env.dusk.local.example
  .github/workflows/dusk.yaml
  composer.json
  composer.lock
  database/factories/UserFactory.php
  resources/views/about.blade.php
  resources/views/components/about/contributors.blade.php
  resources/views/components/navbar/dark-mode-button.blade.php
  resources/views/components/navbar/messages-link.blade.php
  resources/views/components/navbar/navbar.blade.php
  resources/views/components/profile/user-menu/dropdown.blade.php
  resources/views/components/profile/user-menu/menu.blade.php
  tests/Browser/AboutPageTest.php
  tests/Browser/Components/About/Contributors.php
  tests/Browser/Components/Navbar.php
  tests/Browser/Components/Profile/UserMenu/Menu.php
  tests/Browser/EmailVerificationTest.php
  tests/Browser/MainMenuTest.php
  tests/Browser/Pages/AboutPage.php
  tests/Browser/Pages/EmailVerificationPage.php
  tests/Browser/Pages/ProfilePage.php
  tests/Feature/Support/FetchContributorsTest.php
Labels: tests

#309 Moved "to top" button into a separate blade component
  resources/views/components/buttons/to-top.blade.php
  resources/views/layouts/base.blade.php
Labels: refactoring

#310 Moved dark mode switch logic to a separate JS file
  resources/js/app.js
  resources/js/data/general/darkTheme.js
  resources/views/layouts/base.blade.php
Labels: refactoring

#311 Added system theme
  resources/js/data/general/darkTheme.js
  resources/views/components/icons/computer-desktop.blade.php
  resources/views/components/icons/dark-mode.blade.php
  resources/views/components/icons/moon.blade.php
  resources/views/components/icons/sun.blade.php
  resources/views/components/navbar/dark-mode-button.blade.php
Labels: ux/ui, feature

#313 Removed translation functions from home blade file
  resources/views/home.blade.php
Labels: dead code

#331 Fix email verification
  resources/views/emails/email-verification.blade.php
Labels: bug
